version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: .
    environment:
      - DATABASE_URL=postgresql://yourusername:yourpassword@db:5432/yourdatabase
      - SECRET_KEY=mysecretkey
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
